[settings]
enable_tracing = false

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
default_command = "substrate"

chain = "gen-db"
chain_spec_path = "zombienet/0004-webrtc/chain-spec.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = false
  db_snapshot="https://storage.googleapis.com/zombienet-db-snaps/substrate/0001-basic-warp-sync/chains-a233bbacff650aac6bcb56b4e4ef7db7dc143cfb.tgz"
  args = ["--listen-addr", "/ip4/0.0.0.0/udp/30333/webrtc"]

  [[relaychain.nodes]]
  name = "bob"
  validator = false
  db_snapshot="https://storage.googleapis.com/zombienet-db-snaps/substrate/0001-basic-warp-sync/chains-a233bbacff650aac6bcb56b4e4ef7db7dc143cfb.tgz"
  args = ["--listen-addr",  "/ip4/0.0.0.0/udp/30333/webrtc"]

  #we need at least 3 nodes for warp sync
  [[relaychain.nodes]]
  name = "charlie"
  validator = false
  db_snapshot="https://storage.googleapis.com/zombienet-db-snaps/substrate/0001-basic-warp-sync/chains-a233bbacff650aac6bcb56b4e4ef7db7dc143cfb.tgz"
  args = ["--listen-addr",  "/ip4/0.0.0.0/udp/30333/webrtc"]

  [[relaychain.nodes]]
  name = "dave"
  validator = false
  args = ["--listen-addr",  "/ip4/0.0.0.0/udp/30333/webrtc", "--sync warp"]
